name: Create Resource Pack BW v1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    permissions:
      contents: write
    
    steps:
    
      - name: GitHub Tag Name example
        run: |
          echo "======================================================"
          echo "github.ref_name: ${{  github.ref_name }}"
          echo "======================================================"
          echo "github.run_id: ${{  github.run_id }}"
          echo "======================================================"
          echo "github.run_number: ${{  github.run_number }}"
          echo "======================================================"
          echo "github.run_attempt: ${{  github.run_attempt }}"
          echo "======================================================"
          
####################################################################################################################### 
 
      - uses: actions/checkout@v3

      - uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: "RESOURCE_PROJECTBW"
          draft: false
          prerelease: false
 
      - name: RC SB.PROJECTBW.RU
        run: |
          echo "======================================================"
          echo "ГЕНЕРАТОР ТЕКСТУР SB.PROJECTBW.RU"
          echo "======================================================" 
 
      - uses: ksm2/archive-action@v1
        id: archive
        with:
          root-directory: resource_packs/sb.projectbw.ru
          format: "zip"
          name: SB.PROJECTBW.RU
      
      - uses: actions/upload-release-asset@v1.0.1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.path }}
          asset_name: ${{ steps.archive.outputs.name }}
          asset_content_type: ${{ steps.archive.outputs.media-type }}
        
##########################################

      - name: UPLOAD SB.PROJECTBW.RU
        run: |
          echo "======================================================"
          echo "ЗАГРУЗКА ТЕКСТУР SB.PROJECTBW.RU"
          echo "======================================================" 

      - uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          fileName: "SB.PROJECTBW.RU.zip"
          out-file-path: "upload"

      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          #local-dir: ${{ steps.archive.outputs.path }}/
          local-dir: '/home/runner/work/RP_SB.PROJECTBW.RU/RP_SB.PROJECTBW.RU/upload/'
          #server-dir: ${{ secrets.FTP_PATH }}/
          server-dir: /hdd/pterodactyl/volumes/8eca4a8a-9337-4709-87f6-9a622d31795f/plugins/forcepack/packs/
          protocol: ftp
          security: loose
          log-level: verbose
          state-name: .SB.json
          port: 21 # todo replace with your web hosts ftps port


######################################################################################################################################